"""
Extracts proper nouns from wordlist-2/data/scowl-pre.txt (SCOWL project)
and writes a sorted C++ header for binary search at runtime.
Only entries at level <= 60 (well-known words) are included.
"""
import re

SCOWL_FILE = 'wordlist-2/data/scowl-pre.txt'
OUT_FILE    = 'proper_nouns.h'
MAX_LEVEL   = 60

words = set()

with open(SCOWL_FILE, encoding='utf-8') as f:
    for line in f:
        if not re.search(r'<n/(name|upper|place|person)', line):
            continue
        m = re.match(r'^(\d+)', line)
        if not m or int(m.group(1)) > MAX_LEVEL:
            continue
        m = re.search(r':\s+([A-Z][A-Za-z]+)\s+<n/(name|upper|place|person)', line)
        if m:
            words.add(m.group(1))

words = sorted(words)

with open(OUT_FILE, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by gen_proper_nouns.py from SCOWL data (level <= 60).\n')
    f.write('// Do not edit by hand - re-run the script to regenerate.\n')
    f.write(f'// {len(words)} entries.\n\n')
    f.write('static const wchar_t * const kProperNouns[] = {\n')
    for w in words:
        f.write(f'    L"{w}",\n')
    f.write('};\n\n')
    f.write(f'static const int kProperNounsCount = {len(words)};\n')

print(f'Wrote {len(words)} entries to {OUT_FILE}')
